name: whatsup
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0  
  firebase_storage: ^12.0.0

  provider: ^6.1.1
  shared_preferences: ^2.2.2

  image_picker: ^1.1.0
  path: ^1.9.0

  image: ^4.2.0

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ssup2.png"
  min_sdk_android: 21 # android min sdk min:16, default:21

flutter:
  uses-material-design: true
  assets:
    - assets/images/ssup2.png
